name: CI/CD Customer-churn-platform

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install -r requirements-api.txt
          pip install pytest httpx pytest-cov

      - name: Lancer les tests pytest
        run: pytest tests/test_api.py -v

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Récupérer le code complet
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installer git-lfs
        run: git lfs install

      - name: Configurer Git
        run: |
          git config user.email "bouekeomerbocassa@gmail.com"
          git config user.name "Bokassa09"

      - name: Pousser sur Hugging Face
        run: |
          git remote add huggingface https://Bokassa09:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Bokassa09/customer-churn-platform
          git push huggingface HEAD:main --force